#!/usr/bin/env bash
# ============================================================
# src/split/split_manifest.sh — Manifest Write, Read & Validate
#
# The manifest is a plain-text file uploaded to SFTP alongside the
# split parts.  It is the single source of truth for a restore or
# verify operation — it carries everything needed to reconstruct
# and validate the original file without any other metadata.
#
# Manifest format:
#   # split_transfer manifest — generated by split_transfer.sh vX.Y.Z
#   original_ftp_path=<ftp path>
#   original_filename=<basename>
#   original_size=<bytes>
#   original_sha256=<hex>
#   part_size_bytes=<configured part size in bytes>
#   part_count=<N>
#   part_suffix_length=<digit width>
#   part_prefix=<filename>.part.
#   split_date=<ISO8601>
#   sftp_parts_dir=<full SFTP path to parts directory>
#   [parts]
#   <partname>  size=<bytes>  sha256=<hex>
#   <partname>  size=<bytes>  sha256=<hex>
#   ...
#
# Functions provided:
#   write_manifest()        — writes the manifest file to a local path
#   read_manifest()         — sources a downloaded manifest into variables
#   get_manifest_part_hash() — looks up the sha256 for a named part
#   get_manifest_part_size() — looks up the size for a named part
#   verify_manifest_header() — checks that all required header fields
#                              are present and non-empty
#
# Dependency order:
#   Must be sourced after src/core/logging.sh (uses log()).
# ============================================================

# write_manifest LOCAL_PATH FTP_PATH ORIGINAL_SIZE ORIGINAL_SHA256
#                PART_SIZE_BYTES PART_COUNT PART_PREFIX SFTP_PARTS_DIR
#                PARTS_ARRAY_FILE
#
# PARTS_ARRAY_FILE is a plain-text file with one line per part:
#   <partname>  size=<bytes>  sha256=<hex>
# produced by the split phase before this function is called.
write_manifest() {
    local manifest_path="$1"
    local ftp_path="$2"
    local original_filename="$3"
    local original_size="$4"
    local original_sha256="$5"
    local part_size_bytes="$6"
    local part_count="$7"
    local part_prefix="$8"
    local sftp_parts_dir="$9"
    local parts_array_file="${10}"

    cat > "${manifest_path}" <<EOF
# split_transfer manifest — generated by split_transfer.sh v${SCRIPT_VERSION}
original_ftp_path=${ftp_path}
original_filename=${original_filename}
original_size=${original_size}
original_sha256=${original_sha256}
part_size_bytes=${part_size_bytes}
part_count=${part_count}
part_suffix_length=${SPLIT_SUFFIX_LENGTH}
part_prefix=${part_prefix}
split_date=$(date '+%Y-%m-%dT%H:%M:%S')
sftp_parts_dir=${sftp_parts_dir}
[parts]
EOF

    # Append per-part lines from the pre-computed parts array file
    cat "${parts_array_file}" >> "${manifest_path}"

    log "DEBUG" "Manifest written: ${manifest_path} (${part_count} parts)"
}

# read_manifest LOCAL_MANIFEST_FILE
#
# Parses the manifest into shell variables prefixed with MANIFEST_:
#   MANIFEST_ORIGINAL_FTP_PATH
#   MANIFEST_ORIGINAL_FILENAME
#   MANIFEST_ORIGINAL_SIZE
#   MANIFEST_ORIGINAL_SHA256
#   MANIFEST_PART_SIZE_BYTES
#   MANIFEST_PART_COUNT
#   MANIFEST_PART_SUFFIX_LENGTH
#   MANIFEST_PART_PREFIX
#   MANIFEST_SPLIT_DATE
#   MANIFEST_SFTP_PARTS_DIR
#
# Per-part data is stored in two associative arrays:
#   MANIFEST_PART_SHA256[partname]=<hex>
#   MANIFEST_PART_SIZE[partname]=<bytes>
read_manifest() {
    local manifest_file="$1"

    if [[ ! -f "${manifest_file}" ]]; then
        log "ERROR" "Manifest file not found: ${manifest_file}"
        return 1
    fi

    # Declare associative arrays for per-part data
    declare -gA MANIFEST_PART_SHA256=()
    declare -gA MANIFEST_PART_SIZE=()

    local in_parts_section=false

    while IFS= read -r line; do
        # Skip comment lines
        [[ "${line}" =~ ^# ]] && continue
        # Skip blank lines
        [[ -z "${line}" ]] && continue

        # Detect [parts] section marker
        if [[ "${line}" == "[parts]" ]]; then
            in_parts_section=true
            continue
        fi

        if [[ "${in_parts_section}" == false ]]; then
            # Parse header key=value pairs
            local key value
            key="${line%%=*}"
            value="${line#*=}"
            case "${key}" in
                original_ftp_path)   MANIFEST_ORIGINAL_FTP_PATH="${value}" ;;
                original_filename)   MANIFEST_ORIGINAL_FILENAME="${value}" ;;
                original_size)       MANIFEST_ORIGINAL_SIZE="${value}" ;;
                original_sha256)     MANIFEST_ORIGINAL_SHA256="${value}" ;;
                part_size_bytes)     MANIFEST_PART_SIZE_BYTES="${value}" ;;
                part_count)          MANIFEST_PART_COUNT="${value}" ;;
                part_suffix_length)  MANIFEST_PART_SUFFIX_LENGTH="${value}" ;;
                part_prefix)         MANIFEST_PART_PREFIX="${value}" ;;
                split_date)          MANIFEST_SPLIT_DATE="${value}" ;;
                sftp_parts_dir)      MANIFEST_SFTP_PARTS_DIR="${value}" ;;
            esac
        else
            # Parse per-part lines:
            # <partname>  size=<bytes>  sha256=<hex>
            local partname part_size_val part_sha256_val
            partname=$(echo "${line}" | awk '{print $1}')
            part_size_val=$(echo "${line}" | grep -oP 'size=\K[0-9]+')
            part_sha256_val=$(echo "${line}" | grep -oP 'sha256=\K[0-9a-f]+')
            if [[ -n "${partname}" ]] && [[ -n "${part_size_val}" ]] && [[ -n "${part_sha256_val}" ]]; then
                MANIFEST_PART_SIZE["${partname}"]="${part_size_val}"
                MANIFEST_PART_SHA256["${partname}"]="${part_sha256_val}"
            fi
        fi
    done < "${manifest_file}"

    log "DEBUG" "Manifest loaded: ${MANIFEST_PART_COUNT} parts, original=${MANIFEST_ORIGINAL_FILENAME} (${MANIFEST_ORIGINAL_SIZE} bytes)"
}

# get_manifest_part_hash PARTNAME
# Prints the sha256 hex for the named part, or empty string if not found.
get_manifest_part_hash() {
    local partname="$1"
    echo "${MANIFEST_PART_SHA256[${partname}]:-}"
}

# get_manifest_part_size PARTNAME
# Prints the byte size for the named part, or empty string if not found.
get_manifest_part_size() {
    local partname="$1"
    echo "${MANIFEST_PART_SIZE[${partname}]:-}"
}

# verify_manifest_header
# Checks that all required header fields were populated by read_manifest().
# Returns 0 if all present, 1 if any are missing (with ERROR log per missing field).
verify_manifest_header() {
    local errors=0

    check_manifest_field() {
        local field_name="$1"
        local field_value="$2"
        if [[ -z "${field_value}" ]]; then
            log "ERROR" "Manifest missing required field: ${field_name}"
            (( errors++ )) || true
        fi
    }

    check_manifest_field "original_ftp_path"  "${MANIFEST_ORIGINAL_FTP_PATH:-}"
    check_manifest_field "original_filename"  "${MANIFEST_ORIGINAL_FILENAME:-}"
    check_manifest_field "original_size"      "${MANIFEST_ORIGINAL_SIZE:-}"
    check_manifest_field "original_sha256"    "${MANIFEST_ORIGINAL_SHA256:-}"
    check_manifest_field "part_size_bytes"    "${MANIFEST_PART_SIZE_BYTES:-}"
    check_manifest_field "part_count"         "${MANIFEST_PART_COUNT:-}"
    check_manifest_field "part_prefix"        "${MANIFEST_PART_PREFIX:-}"
    check_manifest_field "sftp_parts_dir"     "${MANIFEST_SFTP_PARTS_DIR:-}"

    if (( ${#MANIFEST_PART_SHA256[@]} == 0 )); then
        log "ERROR" "Manifest contains no [parts] entries"
        (( errors++ )) || true
    fi

    if (( errors > 0 )); then
        return 1
    fi
    return 0
}